fix: update Docker run command to use the latest image tag for tests

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -25,6 +25,16 @@ jobs:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
+      - name: Check Docker Username Format
+        run: |
+          echo "Docker Username: ${{ secrets.DOCKER_USERNAME }}"  
+          if [[ "${{ secrets.DOCKER_USERNAME }}" == *[!a-zA-Z0-9_-]* ]]; then  
+            echo "Username format is invalid!"  
+            exit 1  
+          else  
+            echo "Username format is valid!"  
+          fi
+
       - name: 🏗️ Build Docker Image
         run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ecommerce-app:latest .
 
